- InertialMeasurementUnit BACK accX
- InertialMeasurementUnit BACK accY
- InertialMeasurementUnit BACK accZ
- InertialMeasurementUnit BACK gyroX
- InertialMeasurementUnit BACK gyroY
- InertialMeasurementUnit BACK gyroZ
- InertialMeasurementUnit BACK magneticX
- InertialMeasurementUnit BACK magneticY
- InertialMeasurementUnit BACK magneticZ
- InertialMeasurementUnit RUA accX
- InertialMeasurementUnit RUA accY
- InertialMeasurementUnit RUA accZ
- InertialMeasurementUnit RUA gyroX
- InertialMeasurementUnit RUA gyroY
- InertialMeasurementUnit RUA gyroZ
- InertialMeasurementUnit RUA magneticX
- InertialMeasurementUnit RUA magneticY
- InertialMeasurementUnit RUA magneticZ
- InertialMeasurementUnit RLA accX
- InertialMeasurementUnit RLA accY
- InertialMeasurementUnit RLA accZ
- InertialMeasurementUnit RLA gyroX
- InertialMeasurementUnit RLA gyroY
- InertialMeasurementUnit RLA gyroZ
- InertialMeasurementUnit RLA magneticX
- InertialMeasurementUnit RLA magneticY
- InertialMeasurementUnit RLA magneticZ
- InertialMeasurementUnit LUA accX
- InertialMeasurementUnit LUA accY
- InertialMeasurementUnit LUA accZ
- InertialMeasurementUnit LUA gyroX
- InertialMeasurementUnit LUA gyroY
- InertialMeasurementUnit LUA gyroZ
- InertialMeasurementUnit LUA magneticX
- InertialMeasurementUnit LUA magneticY
- InertialMeasurementUnit LUA magneticZ
- InertialMeasurementUnit LLA accX
- InertialMeasurementUnit LLA accY
- InertialMeasurementUnit LLA accZ
- InertialMeasurementUnit LLA gyroX
- InertialMeasurementUnit LLA gyroY
- InertialMeasurementUnit LLA gyroZ
- InertialMeasurementUnit LLA magneticX
- InertialMeasurementUnit LLA magneticY
- InertialMeasurementUnit LLA magneticZ
- InertialMeasurementUnit L-SHOE EuX
- InertialMeasurementUnit L-SHOE EuY
- InertialMeasurementUnit L-SHOE EuZ
- InertialMeasurementUnit L-SHOE Nav_Ax
- InertialMeasurementUnit L-SHOE Nav_Ay
- InertialMeasurementUnit L-SHOE Nav_Az
- InertialMeasurementUnit L-SHOE Body_Ax
- InertialMeasurementUnit L-SHOE Body_Ay
- InertialMeasurementUnit L-SHOE Body_Az
- InertialMeasurementUnit L-SHOE AngVelBodyFrameX
- InertialMeasurementUnit L-SHOE AngVelBodyFrameY
- InertialMeasurementUnit L-SHOE AngVelBodyFrameZ
- InertialMeasurementUnit L-SHOE AngVelNavFrameX
- InertialMeasurementUnit L-SHOE AngVelNavFrameY
- InertialMeasurementUnit L-SHOE AngVelNavFrameZ
- InertialMeasurementUnit L-SHOE Compass
- InertialMeasurementUnit R-SHOE EuX
- InertialMeasurementUnit R-SHOE EuY
- InertialMeasurementUnit R-SHOE EuZ
- InertialMeasurementUnit R-SHOE Nav_Ax
- InertialMeasurementUnit R-SHOE Nav_Ay
- InertialMeasurementUnit R-SHOE Nav_Az
- InertialMeasurementUnit R-SHOE Body_Ax
- InertialMeasurementUnit R-SHOE Body_Ay
- InertialMeasurementUnit R-SHOE Body_Az
- InertialMeasurementUnit R-SHOE AngVelBodyFrameX
- InertialMeasurementUnit R-SHOE AngVelBodyFrameY
- InertialMeasurementUnit R-SHOE AngVelBodyFrameZ
- InertialMeasurementUnit R-SHOE AngVelNavFrameX
- InertialMeasurementUnit R-SHOE AngVelNavFrameY
- InertialMeasurementUnit R-SHOE AngVelNavFrameZ
- InertialMeasurementUnit R-SHOE Compass
- Locomotion
